# Generated by Django 3.1.2 on 2020-12-15 03:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('room', '0001_initial'),
        ('team', '0003_auto_20201129_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('reserve_time', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reserver_id', models.ForeignKey(db_column='reserver_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room_id', models.ForeignKey(db_column='room_id', on_delete=django.db.models.deletion.CASCADE, to='room.room')),
                ('team_id', models.ForeignKey(db_column='team_id', on_delete=django.db.models.deletion.CASCADE, to='team.team')),
            ],
            options={
                'db_table': 'reservation_queue',
            },
        ),
    ]
