# Generated by Django 3.1.2 on 2020-12-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationqueue',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='reservationqueue',
            table='reservation_queue',
        ),
    ]
