# Generated by Django 3.1.2 on 2021-01-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='project',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterModelTable(
            name='linkedteamuser',
            table='LinkedTeamUser',
        ),
        migrations.AlterModelTable(
            name='team',
            table='Team',
        ),
    ]
