# Generated by Django 3.1.2 on 2020-11-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20201129_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='project',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
