# Generated by Django 3.1.2 on 2020-11-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, verbose_name='username')),
                ('email', models.EmailField(max_length=128, primary_key=True, serialize=False, unique=True, verbose_name='email address')),
                ('is_teacher', models.BooleanField(default=False, help_text='Can accept or refuse reservation request', verbose_name='teacher status')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
