# Generated by Django 3.1.2 on 2020-11-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_teacher',
            field=models.BooleanField(default=False, help_text='Can accept or refuse reservation request', verbose_name='teacher status'),
        ),
    ]
