# Generated by Django 3.1.2 on 2020-12-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201129_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.PositiveSmallIntegerField(choices=[(1, 'student'), (2, 'teacher'), (3, 'admin')], primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
