# Generated by Django 3.1.2 on 2020-12-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20201215_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'admin'), (2, 'teacher'), (3, 'student')], default=3),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
