# Generated by Django 3.1.2 on 2020-12-17 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20201214_1932'),
        ('account', '0006_auto_20201215_2239'),
        ('account', '0003_auto_20201214_1453'),
    ]

    operations = [
    ]
